name: Nightly
on:
  schedule:
    - cron: '0 18 * * *' # 6pm Daily
jobs:

  Nightly:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        node: [22.x, 24.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Range
        run: npm run range
      - name: Native TypeScript Compiler
        run: npm run native