import './clone/index'
import './extends/index'
import './guard/index'
import './intrinsic/index'
import './normalize/index'
import './registry/index'
import './template-literal/index'
import './value/index'
